</$objtype/mkfile

CFLAGS=-Fpw -I/sys/include/npe -I/sys/include/npe/SDL2 -D__plan9__ -D__${objtype}__ -DUSE_SDL -DSHAREWARE=0

LIB=libaudio.a

OFILES=\
	fx_man.$O\
	dsl.$O\
	ll_man.$O\
	multivoc.$O\
	mv_mix.$O\
	mvreverb.$O\
	nodpmi.$O\
	pitch.$O\
	user.$O\
	usrhooks.$O\


</sys/src/cmd/mksyslib

